/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#393939',
        'primary': '#ffffff',
        'on-secondary': '#1c1b1b',
        'on-secondary-fixed-variant': '#3c3b3b',
        'on-background': '#e2e2e2',
        'primary-fixed-dim': '#454747',
        'background': '#131313',
        'tertiary-fixed-dim': '#454747',
        'inverse-primary': '#5d5f5f',
        'primary-fixed': '#5d5f5f',
        'on-primary': '#1a1c1c',
        'on-primary-fixed-variant': '#e2e2e2',
        'surface': '#131313',
        'tertiary-container': '#909191',
        'surface-container-lowest': '#0e0e0e',
        'surface-dim': '#131313',
        'on-tertiary-fixed': '#ffffff',
        'secondary-fixed': '#c8c6c5',
        'surface-variant': '#353535',
        'inverse-on-surface': '#303030',
        'outline-variant': '#474747',
        'surface-container-highest': '#353535',
        'surface-container-low': '#1b1b1b',
        'secondary-container': '#474646',
        'on-primary-container': '#000000',
        'inverse-surface': '#e2e2e2',
        'surface-container-high': '#2a2a2a',
        'on-surface-variant': '#c6c6c6',
        'secondary': '#c8c6c5',
        'primary-container': '#d4d4d4',
        'tertiary': '#e2e2e2',
        'on-tertiary-container': '#000000',
        'on-tertiary-fixed-variant': '#e2e2e2',
        'on-error-container': '#ffdad6',
        'on-secondary-container': '#e5e2e1',
        'on-error': '#690005',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'surface-container': '#1f1f1f',
        'tertiary-fixed': '#5d5f5f',
        'on-tertiary': '#1a1c1c',
        'secondary-fixed-dim': '#adabaa',
        'on-secondary-fixed': '#1c1b1b',
        'outline': '#919191',
        'on-surface': '#e2e2e2',
        'surface-tint': '#c6c6c7',
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
        'manrope': ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '9999px',
      },
      animation: {
        'spin-slow': 'spin-slow 8s linear infinite',
      },
      keyframes: {
        'spin-slow': {
          'from': { transform: 'rotate(0deg)' },
          'to': { transform: 'rotate(360deg)' },
        },
      },
    },
  },
  plugins: [],
}
